# Generated by Django 3.2.7 on 2021-09-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField(max_length=4)),
                ('student_name', models.CharField(max_length=100)),
                ('grade_class', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=100)),
                ('student_phone', models.IntegerField(max_length=11)),
                ('field_of_study', models.CharField(choices=[('Arts', 'Arts'), ('Computer Science', 'Computer Science'), ('General Science', 'General Science')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(max_length=4)),
                ('teacher_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('teacher_phone', models.CharField(max_length=11)),
                ('subject_speciality', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
            ],
        ),
    ]
